# Generated by Django 4.2.30 on 2026-05-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QueueEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("phone", models.CharField(max_length=20, verbose_name="Teléfono")),
                ("turn_number", models.PositiveIntegerField(verbose_name="Turno")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Esperando"),
                            ("called", "Llamado"),
                            ("attended", "Atendido"),
                        ],
                        default="waiting",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Registrado"),
                ),
                (
                    "called_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Llamado a las"
                    ),
                ),
                (
                    "attended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Atendido a las"
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno",
                "verbose_name_plural": "Turnos",
                "ordering": ["turn_number"],
            },
        ),
    ]
